### PR TITLE
fix(bmalloc): fixed never re-allocated sections when block-merging

### LINKED ISSUE #19: `Vec` created in Buddy Allocator while running in protected will cause crash when calling `push()` unless creation is made by calling `with_capacity()`

### PR DESCRIPTION
**Pull request by sleiderr**
The `remove_blk` function, which is supposed to remove free blocks when merging was not working as intended.

Closes #19

### CODE REVIEW

File: src/bios/flib/src/mem/bmalloc/heap.rs [hunk 1]
```diff
@@ -226,16 +226,16 @@ impl<const N: usize> BuddyAllocator<N> {
...
+    /// to a given level.
     pub fn level_size(&self, level: u8) -> usize {
         self.min_blk_size << level
     }
 
-    // Remove a given [`FreeBlock`] from free lists.
-    //
-    // Returns `false` if the operation was unsuccessful,
-    // it usually means that the `FreeBlock is in use`.
+    /// Remove a given [`FreeBlock`] from free lists.
```
Comment (raphfaur) [inline src/bios/flib/src/mem/bmalloc/heap.rs:235]:
```suggestion
    /// Remove a given `FreeBlock` from free lists.
```

Comment (raphfaur) [reply src/bios/flib/src/mem/bmalloc/heap.rs:235]: Dont know

**Review by raphfaur — APPROVED** [review]
Good job, hope it will fix all weird bugs related to Vecs
